### ISSUE TITLE
启动闪现业务视图

### ISSUE THREAD

**Issue by XiMouQiu** [li6185377/IMYADLaunchDemo#1]
研究并运行Demo，发先一个体验不好的地方，就是在将要加载出广告视图的时候，会先显示出keywindow的的橙色首页，然后才显示出广告视图，这点在实际应用中体验并不是很好。

**Comment by li6185377** [comment]
你可以把demo里面的渐显动画先关闭。

**Comment by yang6155** [comment]
亲测关闭渐显动画也不管用啊？

**Comment by li6185377** [comment]
```
///要等DidFinished方法结束后才能初始化UIWindow，不然会检测是否有rootViewController
dispatch_async(dispatch_get_main_queue(), ^{
```

把延迟去掉。 不过内部初始化的UIWindow 就需要一个透明的 RootViewController

**Comment by li6185377** [comment]
Demo 我更新了。 你们可以去试下
